### ISSUE TITLE
[Request] assert_location_v1 transactions could return geocode data

### ISSUE THREAD

**Issue by danielcolinjames** [helium/blockchain-http#148]
I'm not sure how feasible it is, but it would be great if transactions of type `assert_location_v1` could return the same "geocode" info as `/hotspots/:address` returns:
![Screen Shot 2020-12-07 at 4 54 07 PM](https://user-images.githubusercontent.com/10648471/101423320-a396d180-38ad-11eb-9e86-2e4112919f8f.png)

so that I could use the city/state/country/street names in things like meta tags or UIs in the frontend without having to make another request.

Come to think of it, it would be great if other transaction types returned the same thing, e.g. `poc_receipts_v1` and `poc_request_v1` — could be useful to display city / street names when showing challenges and their participants in the app or in Explorer

**Comment by madninja** [comment]
The problem with doing it in transaction is that 

1. The transactions don't contain all this data in the database since it's annotated after the fact by having the geocoder fill in the details 
2. As a result of the first, getting geocode data for any transaction that contains hotspots would require additional database queries for every transaction as it's rendering them
3. There are a _lot_ of references to gateways in transactions. This would make transaction retrieval much larger and certainly slower. 

Perhaps we can approach this from the "api user" side and see what you're trying to show/achieve?

**Comment by danielcolinjames** [comment]
Thanks for explaining that! I wanted to have the meta tags for an asserted location transaction say where the hotspot's location was asserted to, e.g.:

![Screen Shot 2020-12-08 at 4 24 26 PM](https://user-images.githubusercontent.com/10648471/101557455-e5894b80-3971-11eb-9ef5-2be4bb621bfe.png)
https://helium-explorer-pr-107.herokuapp.com/txns/TlyotGbYrC7aB2-39weVcdPy10m6nQTUnxuleWF7a3s

I can probably just get what I want with existing endpoints and one extra API call, since that transaction detail page should probably display that data in a nicer way anyway, including the location it was asserted to (so I wouldn't be adding extra API calls just for the meta tags)—so I can add that detail to the meta tags once I revisit this page as a whole.

Thanks though! Just wanted to see if it would be easy. Feel free to close this ticket :)
