### ISSUE TITLE
`security_exchange_v1` is not considered a `payment` type

### ISSUE THREAD

**Issue by cokes518** [helium/blockchain-http#288]
transaction:
https://explorer-v1.helium.com/txns/IQ3SuhzeynAM4HKqkrnSGKx7WjMLsWb24Wio7HcIcV4

api response for the receiver: 
https://api.helium.io/v1/accounts/13t3msUxxgcaiwJeRbV8ngqGN28Dcdi6UGiWxG8ELWrun5MYdgj/activity?filter_types=payment_v1%2Cpayment_v2%2Csecurity_exchange_v1

block 697113

**Comment by madninja** [comment]
I confirmed this as fixed with: 

https://api.helium.io/v1/accounts/13t3msUxxgcaiwJeRbV8ngqGN28Dcdi6UGiWxG8ELWrun5MYdgj/activity?filter_types=security_exchange_v1&max_time="2021-01-30"

and following the returned cursor: https://api.helium.io/v1/accounts/13t3msUxxgcaiwJeRbV8ngqGN28Dcdi6UGiWxG8ELWrun5MYdgj/activity?cursor=eyJ0eXBlcyI6InNlY3VyaXR5X2V4Y2hhbmdlX3YxIiwibWluX2Jsb2NrIjo2OTcwNjgsIm1heF9ibG9jayI6Njk3MjIxLCJibG9jayI6Njk3MjAwLCJhbmNob3JfYmxvY2siOjY5NzIwMH0
